services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: session20-prometheus
    ports:
      - "127.0.0.1:9092:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:12.1.1
    container_name: session20-grafana
    ports:
      - "127.0.0.1:3003:3000"
    depends_on:
      - prometheus
